--[[
    src/features/loader.lua

    REGENERATED by tools/gen-registry.js — do not hand-edit, re-run the tool.

    The OSS release shipped this file as `-- Omitted. Do this yourself. <3`.
    It carries two things the rest of the tree cannot run without:

      1. the global `Feature` — used 123 times. Every module under
         src/features calls it at load time, e.g.
             return Feature:new("no_shadows", scheduler:add_task(2.5), fn)

      2. aztup.features — read by src/utility/ui/wrapper.lua on every toggle:

             local feature = aztup.features[ID];      -- line 323
             if not feature then return end;          -- line 324
             ...
             if Value then feature:enable() else feature:disable() end;

         With the table empty, all 214 toggles in src/ui/tabs/*.lua set their
         flag and then do nothing.

    110 ids resolved to a module. 155 ids have no module —
    those are option flags consumed by other features, not features themselves.
]]

Feature = require("@src/features/generic_feature");

-- ── globals the stripped loader published ──────────────────────────────────
-- Not features. These were set up by the original loader, and their absence
-- is what makes live errors like "attempt to index nil with 'get_ping'".

-- src/utility/latency.lua was only ever assigned from
-- src/features/auto-parry/auto-parry.lua, and nothing requires that module any
-- more, so bare `Latency` was nil. It is read 76 times, including on every
-- animator tick, so it has to exist before any feature loads.
Latency = require("@src/utility/latency");

-- Used 56 times, mostly in the animator handler, and defined nowhere in the
-- release. Silent unless a debug flag is on.
debug_print = function(...)
    if aztup and aztup.flags and aztup.flags.debug then
        print("[pr]", ...);
    end;
end;

local loader = {};

-- id -> module. Generated from the toggle ids in src/ui/tabs/*.lua.
local MODULES = {
    ["aggressive_optimize_game"] = "@src/features/qol/aggressive_optimize_game",
    ["agility_spoofer"] = "@src/features/spoofing/agility_spoofer",
    ["anchor"] = "@src/features/misc/anchor",
    ["anim_speed_changer"] = "@src/features/combat/anim_speed_changer",
    ["anti_afk"] = "@src/features/removals/anti_afk",
    ["ap_breaker"] = "@src/features/exploits/ap_breaker",
    ["apply_fflags"] = "@src/features/misc/apply_fflags",
    ["attach_to_back"] = "@src/features/combat/attach_to_back",
    ["auto_air_counter"] = "@src/features/combat/auto_air_counter",
    ["auto_ardour"] = "@src/features/combat/auto_ardour",
    ["auto_brutus"] = "@src/features/automation/auto_brutus",
    ["auto_chime_requeue"] = "@src/features/automation/auto_chime_requeue",
    ["auto_decline_guild_invites"] = "@src/features/automation/auto_decline_guild_invites",
    ["auto_decline_squad_invites"] = "@src/features/automation/auto_decline_squad_invites",
    ["auto_dustlunge"] = "@src/features/combat/auto_dustlunge",
    ["auto_equip_weapon"] = "@src/features/automation/auto_equip_weapon",
    ["auto_fight"] = "@src/features/auto-fight/auto-fight",
    ["auto_fish"] = "@src/features/automation/auto_fish",
    ["auto_flow_state"] = "@src/features/automation/auto_flow_state",
    ["auto_golden_tongue"] = "@src/features/combat/auto_golden_tongue",
    ["auto_parry"] = "@src/features/auto-parry/auto-parry",
    ["auto_ragdoll_cancel"] = "@src/features/automation/auto_ragdoll_cancel",
    ["auto_reinforce"] = "@src/features/combat/auto_reinforce",
    ["auto_roll_cancel"] = "@src/features/automation/auto_roll_cancel",
    ["auto_sprint"] = "@src/features/automation/auto_sprint",
    ["auto_train_agility"] = "@src/features/automation/auto_train_agility",
    ["auto_uppercut"] = "@src/features/automation/auto_uppercut",
    ["auto_wisp"] = "@src/features/automation/auto_wisp",
    ["backstab_movestacker"] = "@src/features/automation/backstab_movestacker",
    ["brayden"] = "@src/features/qol/brayden",
    ["bring_mobs"] = "@src/features/qol/bring_mobs",
    ["build_stealer"] = "@src/features/misc/build_stealer",
    ["chain_counter"] = "@src/features/visuals/chain_counter",
    ["combosser_detector"] = "@src/features/qol/combosser_detector",
    ["easy_roll_cancel"] = "@src/features/combat/easy_roll_cancel",
    ["endurance_runner_spoof"] = "@src/features/spoofing/endurance_runner_spoof",
    ["experimental_bug_fixes"] = "@src/features/qol/experimental_bug_fixes",
    ["extend_prompts"] = "@src/features/qol/extend_prompts",
    ["fake_void"] = "@src/features/qol/fake_void",
    ["fall_multiplier"] = "@src/features/qol/fall_multiplier",
    ["fast_swing"] = "@src/features/combat/fast_swing",
    ["fly"] = "@src/features/movement/fly",
    ["free_cam"] = "@src/features/visuals/free_cam",
    ["freestylers_band_spoof"] = "@src/features/spoofing/freestylers_band_spoof",
    ["full_bright"] = "@src/features/visuals/full_bright",
    ["girl_detector"] = "@src/features/qol/girl_detector",
    ["give_animation_gamepass"] = "@src/features/qol/give_animation_gamepass",
    ["hair_id_stealer"] = "@src/features/misc/hair_id_stealer",
    ["harrow_remover"] = "@src/features/removals/harrow_remover",
    ["inf_zoom"] = "@src/features/visuals/inf_zoom",
    ["infinite_jump"] = "@src/features/movement/infinite_jump",
    ["jesus"] = "@src/features/qol/jesus",
    ["kamui_teleport"] = "@src/features/exploits/kamui_teleport",
    ["knocked_ownership"] = "@src/features/movement/knocked_ownership",
    ["kongas_spoof"] = "@src/features/spoofing/kongas_spoof",
    ["leaderboard_spectate"] = "@src/features/visuals/leaderboard_spectate",
    ["lightweight_spoof"] = "@src/features/spoofing/lightweight_spoof",
    ["m1_hold"] = "@src/features/combat/m1_hold",
    ["mantra_revealer"] = "@src/features/removals/mantra_revealer/mantra_revealer",
    ["mantra_slidecasting"] = "@src/features/combat/mantra_slidecasting",
    ["minesweeper"] = "@src/features/qol/minesweeper",
    ["mob_ai_breaker"] = "@src/features/exploits/mob_ai_breaker",
    ["mod_detector"] = "@src/features/misc/mod_detector/mod_detector",
    ["multiply_s"] = "@src/features/movement/multiply_s",
    ["no_blind"] = "@src/features/removals/no_blind",
    ["no_blur"] = "@src/features/removals/no_blur",
    ["no_clouds"] = "@src/features/removals/no_clouds",
    ["no_depths_trial_voices"] = "@src/features/removals/no_depths_trial_voices",
    ["no_echo_screen"] = "@src/features/removals/no_echo_screen",
    ["no_fall"] = "@src/features/removals/no_fall",
    ["no_fire"] = "@src/features/removals/no_fire",
    ["no_flame_blind"] = "@src/features/removals/no_flame_blind",
    ["no_fog"] = "@src/features/removals/no_fog",
    ["no_hive_gate"] = "@src/features/removals/no_hive_gate",
    ["no_kill_bricks"] = "@src/features/removals/no_kill_bricks",
    ["no_mob_encounters"] = "@src/features/removals/no_mob_encounters",
    ["no_one_bit"] = "@src/features/removals/no_one_bit",
    ["no_roll_fatigue"] = "@src/features/removals/no_roll_fatigue",
    ["no_sanity_vfx"] = "@src/features/removals/no_sanity_vfx",
    ["no_sea"] = "@src/features/removals/no_sea",
    ["no_shadows"] = "@src/features/visuals/no_shadows",
    ["no_speed_debuff"] = "@src/features/removals/no_speed_debuff",
    ["no_status_effects"] = "@src/features/removals/no_status_effects",
    ["no_stun"] = "@src/features/removals/no_stun",
    ["no_wind"] = "@src/features/removals/no_wind",
    ["no_yun_shul_gate"] = "@src/features/removals/no_yun_shul_gate",
    ["noclip"] = "@src/features/movement/noclip",
    ["optimize_game"] = "@src/features/qol/optimize_game",
    ["parry_sounds"] = "@src/features/qol/parry_sounds",
    ["player_esp"] = "@src/features/visuals/player_esp",
    ["prediction"] = "@src/features/auto-parry/fallbacks/objects/prediction",
    ["proximity_list"] = "@src/features/misc/proximity_list",
    ["race_morph_menu"] = "@src/features/visuals/race_morph_menu",
    ["roll2_revealer"] = "@src/features/removals/roll2_revealer",
    ["sanity_indicator"] = "@src/features/visuals/sanity_indicator",
    ["show_all_on_map"] = "@src/features/visuals/show_all_on_map",
    ["show_chat"] = "@src/features/visuals/show_chat",
    ["silent_aim"] = "@src/features/combat/silent_aim",
    ["snake_game"] = "@src/features/qol/snake_game",
    ["speed"] = "@src/features/movement/speed",
    ["streamer_mode"] = "@src/features/misc/streamer_mode",
    ["talent_highlighter"] = "@src/features/misc/talent_highlighter",
    ["tetris"] = "@src/features/qol/tetris",
    ["tickrate"] = "@src/features/movement/tick_rate",
    ["tp_to_objectives"] = "@src/features/buttons/tp_to_objectives",
    ["vehicle_noclip"] = "@src/features/combat/vehicle_noclip",
    ["vehicle_speed"] = "@src/features/combat/vehicle_speed",
    ["voi_teleport"] = "@src/features/exploits/voi_teleport",
    ["void_mobs"] = "@src/features/qol/void_mobs",
    ["zoom"] = "@src/features/visuals/zoom",
};

-- Ids the UI exposes that have no backing module. These are plain flags other
-- features read out of aztup.flags; there is nothing to instantiate.
local OPTION_ONLY = {
    "action_rolling",
    "action_rolling_chance",
    "aggressive_3_break_on",
    "aggressive_validation",
    "agility_spoof_amount",
    "agility_spoof_health",
    "air_counter_ally_check",
    "air_counter_on_ground",
    "air_counter_range",
    "allow_automation_use_attunements",
    "allow_automation_use_solar",
    "ally_system",
    "anim_speed_changer_types",
    "anti_ap_breaker_debug",
    "anti_ap_breaker_length_ms",
    "anti_ap_breaker_max_speed",
    "anti_ap_breaker_minimum_wt",
    "ap_breaker_intensity",
    "ap_breaker_type",
    "ap_randomization",
    "apply_mouse_sens",
    "atb_lock_rotation",
    "atb_prevent_voiding",
    "atb_rotate",
    "atb_speed",
    "atb_x_offset",
    "atb_y_offset",
    "atb_z_offset",
    "auto_builder_shrined",
    "auto_builder_url",
    "auto_charisma",
    "auto_dustlunge_bind",
    "auto_dustlunge_debug",
    "auto_feint",
    "auto_golden_tongue_mode",
    "auto_math_book",
    "auto_parry_debug",
    "auto_progress_method",
    "auto_progress_shrined",
    "auto_progress_url",
    "auto_saramed_attach_to_mob_distance",
    "auto_saramed_minimum_health",
    "auto_sprint_delay",
    "auto_wisp_delay",
    "automation_config_mode",
    "automation_webhook",
    "basic_validation",
    "bi_punishable_time",
    "block_input",
    "bluff_feint_chance",
    "boat_speed",
    "breaker_type",
    "chance_dodge_weight",
    "chance_parry_weight",
    "chance_skip_weight",
    "chest_esp_show_opened",
    "chime_safety",
    "custom_server_id",
    "disallow_scaling_multiplier",
    "dmg_amount",
    "dont_noclip_while_knocked",
    "dont_process_mobs_over_studs",
    "dont_process_players_over_studs",
    "drop_range",
    "esp_boxes",
    "esp_fadeout",
    "esp_fadeout_hover",
    "esp_healthbar",
    "esp_nametags",
    "esp_update_rate",
    "extra_bi_punishable_time",
    "fakelag",
    "fakelag_amount",
    "fall_multiplier_slider",
    "feint_chance",
    "fly_speed",
    "force_chime_opponent",
    "force_no_tween_ping_comp",
    "force_tween_speed",
    "force_tween_speed_value",
    "fov_filled",
    "fov_radius",
    "fov_transparency",
    "free_cam_speed",
    "fullbright_intensity",
    "gender_detector_genders",
    "gm_color",
    "guildbase_teleport_type",
    "hb_trans",
    "hide_game_esp",
    "hide_sprint_state_bind",
    "hop_type",
    "ignore_ground",
    "info_logger",
    "info_logger_range",
    "jump_power",
    "log_speed_changes",
    "loot_options",
    "mantra_slidecasting_chance",
    "max_boxes",
    "max_momentum_spoof",
    "max_player_distance",
    "max_speed_mult",
    "max_tick_rate",
    "min_speed_mult",
    "min_tick_rate",
    "mob_esp_healthbar",
    "no_aerials",
    "no_castle_light_gate",
    "no_enforcer_pull",
    "no_respawn_time",
    "no_rosen_fire",
    "noclip_camera",
    "notify_in_range",
    "notify_on_loot",
    "notify_with_sound",
    "offset_down",
    "offset_floor",
    "offset_up",
    "only_convert_dodge_if_possible",
    "only_minimum_fall_dmg",
    "only_near_players",
    "parry_sound_type",
    "parry_sound_volume",
    "parry_to_dodge_chance_critical",
    "parry_to_dodge_chance_m1",
    "parry_to_dodge_chance_spells",
    "parry_to_dodge_chance_undefined",
    "parry_to_fallback_chance",
    "player_fadeout_distance",
    "player_proximity_range",
    "player_proximity_vol",
    "posture",
    "pull_to_ground",
    "reveal_animations",
    "safe_spot",
    "sanity",
    "show_fov",
    "show_hitbox_simulation",
    "show_list",
    "show_stored_damage",
    "show_timing_builder",
    "snake_difficulty",
    "stat_editor",
    "steal_dropped_items",
    "switch_speeds",
    "talent_highlighter_url",
    "task_concurrency",
    "text_size",
    "validation_filters",
    "varying_anims",
    "view_hitboxes",
    "vw_color",
    "walk_speed",
    "zoom_sens_mult",
};

function loader.initialize()
    local loaded, failed, skipped = 0, 0, 0;

    for id, module in pairs(MODULES) do
        if aztup.features[id] then
            loaded = loaded + 1;
            continue;
        end;

        local ok, feature = pcall(require, module);
        if not ok then
            failed = failed + 1;
            warn(string.format("[features] %s (%s) failed to load: %s", id, module, tostring(feature)));
            continue;
        end;

        if feature == nil then
            -- Side-effect module. src/features/auto-parry/auto-parry.lua is the
            -- example: it returns nil, but requiring it installs the projectile
            -- handlers and publishes getgenv().DefendActionManager, which
            -- animator-handler calls 56 times. It is flag-driven, not a Feature,
            -- so there is nothing to register — loading it is the whole job.
            loaded = loaded + 1;
        elseif type(feature) == "table" and type(feature.disable) == "function" then
            aztup.features[id] = feature;
            loaded = loaded + 1;
        elseif type(feature) == "table" then
            -- A plain table, not a Feature. Registering it would make
            -- init.lua's detach call a disable() that does not exist
            -- ("[detach none] attempt to call missing method 'disable'").
            skipped = skipped + 1;
        elseif type(feature) == "function" then
            -- button-style module: the UI wires these through Func, not features
            aztup.functions = aztup.functions or {};
            aztup.functions[id] = feature;
            loaded = loaded + 1;
        else
            failed = failed + 1;
            warn(string.format("[features] %s (%s) returned %s", id, module, type(feature)));
        end;
    end;

    if skipped > 0 then
        warn(string.format("[features] %d module(s) returned a plain table, not registered", skipped));
    end;

    getgenv().DECAY_registry = { loaded = loaded, failed = failed, modules = MODULES, options = OPTION_ONLY };

    if not aztup.silent_mode and Logger and Logger.log then
        Logger.log(string.format("[features] registered %d, failed %d", loaded, failed));
    end;
end;

function loader.get(id)
    return aztup.features[id];
end;

function loader.is_option(id)
    return table.find(OPTION_ONLY, id) ~= nil;
end;

-- >>> HAND-WRITTEN
-- Nothing hand-written yet. Anything placed between the HAND-WRITTEN
-- markers survives `node tools/gen-registry.js` verbatim. Everything
-- above them is regenerated from the tree and will be replaced.
-- <<< HAND-WRITTEN

return loader;
